### ISSUE TITLE
Password-less auth using XMPP?

### ISSUE THREAD

**Issue by poVoq** [etesync/server#141]
There is a nice tutorial for adding password-less auth via XMPP to a Django app:
https://blog.agayon.be/xmpp_auth_django.html

https://blog.agayon.be/xmpp_auth_django_demo.html

The updated XMPP server component can be found here:
https://gitlab.com/jnanar/HTTPAuthentificationOverXMPP

I think this would be a really nice addition to an e2ee hosted service as it would allow authentication through an secure channel without sharing any passwords or such.

**Comment by tasn** [comment]
Thanks for the suggestions, though unfortunately this can't work with Etebase.
We actually don't use Django authentication but rather our own secure scheme that relies on the encryption key. The whole idea of e2ee is that the sever can't access the data without the encryption key, so any such authentication methods, which rely on the server doing the auth, can't possibly work. You have to be able to pass the encryption key.

I'm closing it because it can't be done.

**Comment by poVoq** [comment]
That's too bad. Is there an easy way to do the reverse? Authenticating another software like a XMPP server against the etesync server?

**Comment by tasn** [comment]
We could potentially add OAuth to the server to do that, yeah. Though I don't think many people would use it TBH.

You can check out #53 which is semi-relevant.
