### ISSUE TITLE
Add wiki page

### ISSUE THREAD

**Issue by Salt-Factory** [etesync/server#34]
Hi @tasn,

Recently I made a Reddit post in which I said I was planning on updating documentation for a basic installation of the server. Currently, the README points to the wiki for details on a proper production setup, but no such page exists yet. I was wondering: how would I go about updating the wiki?

Last weekend, I reinstalled an EteSync server on my Raspberry Pi, and wrote down everything I did to make it work. From this, I constructed a tutorial page specifically for the Raspberry Pi, on how to install the server using uWSGI and Nginx, on my [personal website](https://simonvandevelde.be/Guides/html/Tutorials/etesync.html#etesync-server). 

Now I would like to add a generic install guide (so not just for the Pi) to the wiki. It would detail how to pull the repo, setting up uWSGI (using a socket file), setting up Nginx and finally setting up TLS. It would be Ubuntu-specific, but converting it to Arch or Fedora is rather simple. All the information for the setup I got from the uWSGI wiki and the example setup files already included in the repo.

Kind regards,
Saltfactory

**Comment by Salt-Factory** [comment]
I forgot to say: setting up systemd to automatically boot uWSGI could also be included.
Basically, everything from pulling the repo to having a fully fledged useable server.

**Comment by tasn** [comment]
Nice catch, I changed the wiki permissions, you should now be able to edit.

As for the content: sounds great, please go ahead and create it! Try to keep instructions simple and feel free to create multiple pages as makes sense. I skimmed through your post (I'm currently at fosdem so not much time), and looks good! Only comment:
```
allowed_host1 = *
```
You should set it to the real host you'll be using rather than *. :)

I'm closing this ticket, as I solved the access issue, but please feel free to reopen if I missed anything.
