### ISSUE TITLE
Looking for best way to update server records

### ISSUE THREAD

**Issue by Salt-Factory** [etesync/server#48]
Hi tasn and others,

Recently, the Pi on which I host the server crashed and got corrupted.
I reverted the Pi to a backup (a full copy of the SD card), with a working EteSync server on it.
However, this server is missing a month and a half of updates, and the EteSync app won't sync to it. (saying Calendar sync failed).

What would be the best way to update the data base on my server?

In the past, I always just made a new account, imported all my old data and deleted the old account. However, it seems like there should be a better solution to this. ;-)

P.S. I have already exported all data locally on my phone, so there is no risk of losing it all.

Thanks in advance.
Kind regards,
Simon

**Comment by tasn** [comment]
Sorry to hear about your Pi. :|

The reason why the app won't sync to it is because it thinks the server has rolled back data and is trying to hide information from users. That's as intended. :)

As for bringing back the data to your server: it's possible, because EteSync keeps a full local copy of everything. However, it's not currently implemented, and probably won't be until the new version of the protocol, because as you might expect, this is a very rare situation. :|

I think your best bet is to just export and re-import as you suggested. Sorry. ;\

--
Tom

**Comment by Salt-Factory** [comment]
Thanks for the answer.

Part of the fun of hosting stuff on a Pi is that it could crash at any point in time anyway. ;-)
Luckily, importing and exporting everything is only 5 minutes of work.
Again, thanks for the effort on this great system! :-)

**Comment by tasn** [comment]
Haha, for sure. My Pi's sdcard got corrupted a few times...
