### ISSUE TITLE
Moving events between calendars

### ISSUE THREAD

**Issue by lonkaars** [etesync/server#49]
I have multiple calendars set up so I can color-code my events, but I can't seem to move events between calendars. I can create new events in all calendars. This happens both in my phone's calendar app and the etesync web client.

**Comment by tasn** [comment]
Sorry for not replying before. I though I already have!

By your phone's calendar app you mean on Android? Because on Android you are not using the EteSync UI, it's the calendar app that needs to support it.

On the web client: indeed it's not implemented. Could you please open a ticket there?

I'm closing this ticket as it's not an issue with the server, but rather with the clients.
