### ISSUE TITLE
User not properly init

### ISSUE THREAD

**Issue by Salt-Factory** [etesync/server#55]
Hi,

Today I created a self-hosted instance of the EteBase server.
As mentioned in the readme, I created an admin user, and then used it to login and created a normal user.

However, now when I want to login through the etesync-dav bridge or using the online login (https://pim.etesync.com/login) I get the error `User not properly init`.
When trying to login using my admin account, I get the exact same error.

Did I miss a step anywhere? Thanks in advance.

**Comment by Salt-Factory** [comment]
Interestingly enough, this error is also given when inputting a wrong password.
However, in this case I am 100% certain the password is correct, as it does work when logging into the Django console.

**Comment by tasn** [comment]
Ohhh, the README is outdated! I'll update it tomorrow...
Essentially the user creation has changed. There is just one password nowadays instead of two previously, so you can no longer create the user on the server. Furthermore, you should *not* set a password at all for a new user on the server. It should have an invalid password so you can't log into it with a password.
To create a new user you need to just "signup" from the app (and use your self-hosted server as the server). I haven't pushed the code for limiting registrations in the self-hosted repo yet, but will try to do it tomorrow. It's mostly there, just need to push an example and one line of code.

**Comment by Salt-Factory** [comment]
Cool, thanks!

**Comment by tasn** [comment]
Done!

**Comment by Salt-Factory** [comment]
Thanks, I got it working! 
It's a bit odd that the account creation can only be done through the app though. Are there any plans on also including this in the DAV-bridge or the online login?

**Comment by tasn** [comment]
It can also be created through the web app: https://pim.etesync.com, it's just the DAV bridge and the KDE/Evolution modules that don't support it yet. The reason it's a bit different now is because creating an account means also setting up the encryption (rather than the two-step before), so you have to do it from a secure client (as we don't want the server exposed to the encryption key).

Btw, are you a Matrix/IRC user? If so please consider joining us at https://www.etesync.com/community-chat/ would be great for more rapid communication.
