### ISSUE TITLE
Self-Hosted Server Cannot Login/Create Account w/ New User on Android App

### ISSUE THREAD

**Issue by anon909** [etesync/server#58]
With a self-hosted server I cannot login/create account with a new user on the Android app.

Successfully created a new user as an admin on the website - but when doing the "add account" section with the advanced settings to the put the custom IP address in the Android app to basically login, no matter what I try, I can't login. The server is clearly showing the attempt, so it's successfully connecting, but keeps suggesting the login details are wrong despite constantly double-checking that everything is correct.

Did something change? What used to be the "username" field is now an "Email" field in the app. I tried adding emails to the user in question and using the email address to try logging in but that never worked either.

Thanks for any help!

**Comment by tasn** [comment]
If you just installed the self-hosted server from master, then it won't work with the current released Android apks because the current master is EteSync 2.0.
For that you would need the APK from https://blog.etesync.com/etesync-2-0-ready-for-testers/
Or wait until we release 2.0 in the next few days.

I'm closing this ticket, but please reopen if it doesn't solve it for you.
